[app]
app_title = "GSLogger"
version_number = [ 0, 2, 58,]
build_number = 111
f_count = 3
atf_pattern = ".txt"

[dev]
developer = "Gregory Denyes"
dev_email = "Greg.Denyes@gmail.com"
dev_link = "https://github.com/friargregarious"
